### ISSUE TITLE
人脸搜索页面底部栏加载出错

### ISSUE THREAD

**Issue by FuryMartin** [FuryMartin/Picf#4]
# 人脸搜索页面底部栏加载出错
## 现象描述
当从人脸搜索页面切出去再切回来，底部信息显示错误。
## 解决方法
优化底部信息显示逻辑。

**Comment by FuryMartin** [comment]
在 commit `#93 解决了issue #2 #4的问题` 中解决。

**Comment by ZhangtaoTaobao** [comment]
OSError: No file or directory found at Models/facenet.h5
训练模型打不开

**Comment by FuryMartin** [comment]
> OSError: No file or directory found at Models/facenet.h5 训练模型打不开

详见 #14

**Comment by ZhangtaoTaobao** [comment]
谢谢&nbsp;





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2025年2月26日(星期三) 中午11:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [FuryMartin/Picf] 人脸搜索页面底部栏加载出错 (Issue #4)












    
OSError: No file or directory found at Models/facenet.h5 训练模型打不开
  
详见 #14

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;
  FuryMartin left a comment (FuryMartin/Picf#4)
  
OSError: No file or directory found at Models/facenet.h5 训练模型打不开
  
详见 #14
